[package]
name = "lab2"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
thirtyfour = "0.35.0"
tokio = { version = "1.43.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
